# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Test Lemonade Server

on:
  push:
    branches: ["main"]
    paths:
      - '**.py'
      - '**.yml'
  pull_request:
    paths:
      - '**.py'
      - '**.yml'
  merge_group:
    paths:
      - '**.py'
      - '**.yml'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  make-server-lemonade:
    env:
        LEMONADE_CI_MODE: "True"
    strategy:
      matrix:
        python-version: ${{ (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event_name == 'workflow_dispatch' && fromJSON('["3.10", "3.11", "3.12", "3.13"]') || fromJSON('["3.12"]') }}
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.os }}-py${{ matrix['python-version'] }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Create virtual environment and install dependencies
        shell: bash
        run: |
          python -m venv .venv
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            source .venv/Scripts/activate
          else
            source .venv/bin/activate
          fi
          python -m pip install --upgrade pip
          python -m pip check
          pip install -e .[dev,oga-cpu]
          lemonade-server-dev pull Qwen2.5-0.5B-Instruct-CPU
          lemonade-server-dev pull Llama-3.2-1B-Instruct-CPU
      - name: Run server tests (unit tests)
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            source .venv/Scripts/activate
          else
            source .venv/bin/activate
          fi
          python test/server_unit.py
      - name: Run Model Manager Tests
        shell: bash
        run: |
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            source .venv/Scripts/activate
          else
            source .venv/bin/activate
          fi
          python test/model_manager.py
      - name: Run server tests (network online mode)
        shell: bash
        run: |
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            source .venv/Scripts/activate
          else
            source .venv/bin/activate
          fi
          python test/server.py
      - name: Run server tests (offline mode)
        shell: bash
        run: |
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            source .venv/Scripts/activate
          else
            source .venv/bin/activate
          fi
          python test/server.py --offline

# This file was originally licensed under Apache 2.0. It has been modified.
# Modifications Copyright (c) 2025 AMD
